Add sequence ordering with react-beautiful-dnd.
samwightt/scrapyard pull request #1
Opened 2020-11-11 00:45 UTC by samwightt

2020-11-11 01:06 UTC, jraisane requested changes

2020-11-11 01:06 UTC, jraisane commented on src/views/sequences/View.tsx
> +          const newSequence = await DataStore.save(
It's certainly not a blocker for merging, but consider moving calls into DataStore into it's own class. 

`const newSequence = await DataStoreWrapper.ReorderSequence(draft, result.source.index, newIndex)`

is much more readable. Instead of needing to know the inner workings of DataStore and array_move, someone can just read that line and say "Oh, we're reordering the sequence." Plus it helps with testability, etc.

2020-11-12 22:48 UTC, samwightt commented on src/views/sequences/View.tsx
> +          setS(() => [...vals]);
Yep! Changed it to `setComponentThoughts`.

2020-11-12 22:50 UTC, samwightt commented on src/views/sequences/View.tsx
> +          result.destination &&
Yep! Question mark just needs to go after the `destination` and we're good.

2020-11-12 23:35 UTC, samwightt commented on src/views/sequences/View.tsx
> +          const newSequence = await DataStore.save(
Definitely! I added an example hook to the lib that sort-of accomplishes this called `useMultiQuery` (and another one called `useSingleQuery` cause I couldn't get the type annotations right). Basically it has the same function signature as `DataStore.query`, but abstracts away all of the `useEffect` mess I was having to do before. I think it cleans up the code quite a bit.

And definitely down to move things into their own class, especially mutations like that. I think it might actually be possible to build them on top of the existing model classes.

2020-11-12 23:36 UTC, samwightt commented
Ready for re-review on this. Changes should've been made!

2020-11-12 23:42 UTC, jraisane approved these changes
Looking good!

2020-11-12 23:43 UTC, merged